sampling_rate_mode : 1  # 0: constant, 1: poisson
sampling_rate_expectation : 5
continuity_mode : 0  # 0: i.i.d, 1: realistic
continuity_max_length : 20
topic_queue_size: 5
subscriber_sample_rate: 10
publisher_duration: 100