sampling_rate_mode : 1  # 0: constant, 1: poisson
sampling_rate_expectation : 100
continuity_mode : 1  # 0: i.i.d, 1: realistic
continuity_max_length : 20
topic_queue_size: 6
subscriber_sample_rate: 200
publisher_duration: 100